version: '3'
services:
  java-srv:
    build:
      context: java-srv
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - "db:db"

  db:
    build:
      context: db
    volumes:
      - ./db/data_dump:/var/opt/mssql
